### ISSUE TITLE
Parametrize repo URL

### ISSUE THREAD

**Issue by dtitenko** [cristiango/release-notes-generator#1]
Current implementation has [repo URL hardcoded](https://github.com/cristiango/release-notes-generator/blob/master/index.js#L26) would be good to have an option to generate release notes for other repos.

**Comment by cristiango** [comment]
Fixed aaf7ebefbbff227a553ca7e779f7aaf2a7285fb9

**Comment by dtitenko** [comment]
😮  w/o PR?

**Comment by cristiango** [comment]
💥
